### ISSUE TITLE
How to describe the state of a sample during characterisation

### ISSUE THREAD

**Issue by jsimonclark** [emmo-repo/domain-characterisation-methodology#12]
What is the recommended way to describe the state of a sample at the time when a characterisation is performed? 

For example, if I perform ElectrochemicalImpedanceSpectroscopy on a Battery with a state-of-charge of 50%. The state-of-charge is a property of the battery, but only at the time of the characterisation. Could it instead be seen as a parameter of the sample preparation procedure (i.e. a SamplePreparationParameter)? Or maybe a MeasurementParameter?

Another example might be the Temperature of an Electrolyte sample during a characterisation of its IonicConductivity.

**Comment by jsimonclark** [comment]
My proposal for expressing this based on the current vocabulary would be something like:

```
{
    "@type": "ElectrochemicalImpedanceSpectroscopy",
    "hasSampledSample": {
        "@type": "BatteryCell"
    },
    "hasMeasurementParameter": {
        "@type": "StateOfCharge",
        "hasNumericalPart": {
            "@type": "Real",
            "hasNumericalValue": 0.5
        },
        "hasMeasurementUnit": "UnitOne"
    }
}
```

But there are some hang ups in the logic, e.g.:

- ElectrochemicalImpedanceSpectroscopy is a CharacterisationMethod; how to link it to a CharacterisationMeasurementProcess?
- The domain of hasSampledSample is SamplingProcess - is it necessary to define this as a subprocess of CharacterisationMeasurementProcess?
- It's a semantic grey zone to me if the state of the sample is a measurement parameter. I could see arguments for and against.

**Comment by pierluigidelnostro** [comment]
Strictly speaking about the CharacterisationMeasurementProcess, both the Battery's StateOfCharge and the Electrolyte's Temperature seem to be properties of the Sample. 
They could be just characteristics of the Sample (declared) or part of the output of the CharacterisationMeasurementProcess, in case they are actually measured by the CharacterisationInstrument.
In case the Battery Sample is prepared with 50% of charge, because it is required by the following CharacterisationMeasurementProcess, then this is a SamplePreparationParameter.

It is also possible to represent different statuses of the Sample over time by using the hasTemporalPart property.

In the picture below, where the cyan classes are invented as part of a specific battery ontology, I have represented the case where the state of charge is also a sample preparation parameter, with the representation of the two statuses of the sample. Here there is a simplified representation of the numerical data and without the measurement unit that you can obviously add.

![CHAMEO Ontology - BatteryExample](https://github.com/emmo-repo/domain-characterisation-methodology/assets/77275273/4ce5d6f5-7972-4b1e-860e-51d3e64f73fb)

Please, do not use the property hasSampledSample, which is specific for the SamplingProcess. The CharacterisationMeasurementProcess hasTemporaryParticipant Sample. We didn't add a specific object property. Will do.

Below a brief clarification on the structure of the classes to describe a characterisation process:
- CharacterisationProcedure is the process of performing characterisation by following some existing formalised operative rules. As subclasses it incudes the following:
- CharacterisationMethod is the class used for the taxonomy of characterisation methods. Each subclass of it is the description of the method regardless of the details and the role in a characterisation process.
- CharacterisationWorkflow is a characterisation procedure that has at least two characterisation tasks as proper parts.
- CharacterisationTask is a task of a CharacterisationWorkflow
- CharacterisationMeasurementProcess is the measurement process associating data to the sample through a probe and a detector. 

![immagine](https://github.com/emmo-repo/domain-characterisation-methodology/assets/77275273/f172a0c4-2a36-4ca8-82f8-cf1e33bd7b4c)

This structure is conceived to give the flexibility to describe, as an example, ElectrochemicalImpedanceSpectroscopy  as a characterisation method in general with a textual description and part of a taxonomy, as a CharacterisationMeasurementProcess (which can be decomposed in more specific tasks) or as a CharacterisationWorkflow where the measurement is one of the tasks.

Hope that helps.
