### ISSUE TITLE
Example: Measuring the mass of a battery

### ISSUE THREAD

**Issue by jsimonclark** [emmo-repo/domain-characterisation-methodology#13]
As discussed in our last meeting, we should make some examples of usage to include in the documentation. I am proposing a few simple and common characterisation processes to get us started. 

**Title**: Measuring the mass of a battery 
**Description**: A battery cell is placed on a scale, which returns a real number that is assigned as the value of the mass of the battery in grams.
**Proposed Pseudo-JSON-LD**:
```
{
    "@type": "chameo:CharacterisationMeasurementProcess",
    "skos:prefLabel": "WeightMeasurementProcess",
    "hasTemporaryParticipant": [
        {
            "@type": ["Sample", "BatteryCell"],
            "hasProperty": {
                "@type": "Mass",
                "hasNumericalPart": {
                    "@id": "my_raw_data"
                },
                "hasMeasurementUnit": "emmo:Gram"
            }
        },
        {
            "@type": "chameo:CharacterisationInstrument",
            "skos:prefLabel": "Scale"
        }
    ],
    "hasOutput": {
        "@id": "my_raw_data",
        "@type": ["chameo:RawData", "Real"],
        "hasNumericalValue": 50
    }
}
```
**Proposed Diagram**:
![onto_test drawio (1)](https://github.com/emmo-repo/domain-characterisation-methodology/assets/52653938/56711f58-9dfb-40eb-94c9-7aa06cd95742)

**Questions** (@pierluigidelnostro):
- [x] Is this the correct usage of chameo terms?
- [ ] How should we handle very common measurement processes / methods like, e.g. WeightMeasurementProcess? 
I propose that we include them for the main "base quantity" measurements (e.g. TimeMeasurement, TemperatureMeasurement, LengthMeasurement, VolumeMeasurement, ElectricPotentialMeasurement, ElectricCurrentMeasurement, ForceMeasurement / WeightMeasurement, PressureMeasurement, ...)
- [ ] How should we handle very common instruments like a Scale? 
As above, I propose we add the basic ones (e.g. Scale, Thermometer, Thermocouple, Clock, Ruler, VolumetricFlask, Pipette, ...) It might get to be a bit much, but they need to be included somewhere and they are too common to go into a more specific domain ontology. 
- [ ] In this example, how to handle the fact that the scale is technically measuring a force (which is the weight) and it is converted to the mass because we assume some acceleration due to gravity (9.81... m/s2). Or is that necessary if the raw data that the scale outputs is a reading of 50 g?

**Comment by pierluigidelnostro** [comment]
Point 1 yes.
For the points 2 and 3 I would not add them in CHAMEO becasuse are not concepts that are valid across all the characterisation techniques. In my opinion they should be in more specific ontologies. Maybe we could do some modules for that, with taxonomies.
For point 4 I think the interest here is on the characterisation instrument and its output, not on the details about how the instrument works internally.

**Comment by jsimonclark** [comment]
Thank you very much @pierluigidelnostro. 

If you think points 2 and 3 should go into more specific domain ontologies, then I could put them into domain-electrochemistry or domain-battery...but I still think that they would be better placed on a higher / more general level.

**Comment by pierluigidelnostro** [comment]
Thanks @jsimonclark for raising that point, which I believe is important and requires an internal discussion to take a decision.

Many concepts in CHAMEO can become a taxonomy (calibration, measurement, measurement parameter, instrument, characterisation property, etc.). I would not add these taxonomies into CHAMEO because it woud distort it and make it heavier. What we have done so far is, based on the CHAMEO generic concepts, to add taxonomies in the technique-specific ontologies (e.g. Nanoindentation, FIB-DIC, Battery discharge testing). We can proceed that way, by having a modular approach related to the type of technique, for example having a set of taxonomies for Mechanical Testing embracing all the concepts valid for all the sub-techniques (Nanoindentation, Fatigue, etc.) each of which with specialised taxonomies when needed. There could even be a higher level in case of concepts that are valid across multiple techniques. As an example, there might be a Characterisation Instruments ontology with the concept of Scale, which can be specialised in a DunnoWhatTypeOfScale in a technique-specific ontology.

I will keep thinking about it an keep you posted
